### ISSUE TITLE
doesn't play nice with Launchpad95

### ISSUE THREAD

**Issue by tolgraven** [dataf1ow/eb.Scrubber#1]
With Launchpad95 you only reach User 2 mode after three presses on that button. It's coded so that M4L devices work anyways and don't notice that fact, but that's definitely not the case for this one. Are you checking mode in a nonstandard way?

I'll try to have a look, in the meantime if anyone knows an easy solution I'd much appreciate it!

**Comment by dataf1ow** [comment]
I never intended for this to have Launchpad95 support, but I might consider it if it's not too much work. I'm not 'checking mode in a nonstandard way', I am checking the mode of the LP script, not the LP95 script. A lot of the device depends on the control surface that is loaded, and I did ZERO testing or implementation for LP95. I doubt it will work at all as is. 

I'll take a look at it later today and see how hard it will be to add support.

**Comment by tolgraven** [comment]
Fair play, what I meant is LP95 is built so that most m4l devices do
function perfectly well without modification, despite the changes to how
user mode 2 is reached. Bang is supposed to be sent on reaching user mode
2, not upon first press - that's why I was wondering if you're doing
something unorthodox

Anyways, cheers man! Awesome little device. I might try to do a little work
on it later on, like locking to tracks by name/id instead of track number,
and slip mode.

**Comment by dataf1ow** [comment]
Unorthodox? I am observing the mode_index. About as orthodox as you can get. 
When you say it sends a bang, a bang out of what? From where? 

I don't think it's the way that I am checking mode, it's the fact that my device looks for scripts based on name. If that name doesn't exist in the loaded control surfaces, no dice. That's why it's not working. If the LP95 is set up to work seamlessly, it'll probably be no more than a drag and drop affair. 

Sip Mode?

**Comment by tolgraven** [comment]
Hmm weird cause it does show up on the LP when you init then add
tracks/change colors, just nothing happens after that. So it's def doing
something.

Slip mode like flux mode in traktor, keep counting where you "would've"
been in the sample and resume from that position when you stop mashing
buttons, in a quantized way so everything keeps synced up.

**Comment by dataf1ow** [comment]
The LP95 script has the Mode Index component in a different place then the original lp script. So when you enter User Mode 2 with the LP95, the device doesn't ever get notified, so it doesn't refresh the LEDs (or do other initialization things that are important to the device), It won't take too long to get this working with LP95, should have it done in the next few days. 

As for 'slip mode', I implemented something like that on my audio looping device, it wouldn't be too tough.  If you want to try to implement it on your own, be my guest, but it can be a little tricky, depending on how you want it to behave. I didn't put anything like that in here, because it didn't make a lot of sense to me, I didn't want to force the user to stay in perfect time. But as an option for each track, it could be useful.

**Comment by dataf1ow** [comment]
Check 1.2. Didn't take long to get it working :). Thanks for checking it out and letting me now it wasn't working for you!
